version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "hello"
      
  test:
    macos:
      xcode: "9.0"
    working_directory: ~/demo
    steps:
      - checkout
      - run: echo "test-hi"
      
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
